from __future__ import annotations

import xml.etree.ElementTree as ET

from .config import ConnectionValues, ConnectorProfile
from .xml_util import BNS, qname, tostring


def build_connection_xml(
    *,
    name: str,
    folder_id: str,
    profile: ConnectorProfile,
    values: ConnectionValues,
) -> str:
    root = ET.Element(
        qname(BNS, "Component"),
        {
            "componentId": "",
            "version": "1",
            "name": name,
            "type": "connector-settings",
            "subType": profile.sub_type,
            "folderId": folder_id,
        },
    )

    encrypted = ET.SubElement(root, qname(BNS, "encryptedValues"))
    password_field_id = profile.connection_fields["password"]
    ET.SubElement(
        encrypted,
        qname(BNS, "encryptedValue"),
        {"isSet": "true", "path": f"//GenericConnectionConfig/field[@id='{password_field_id}']"},
    )

    ET.SubElement(root, qname(BNS, "description")).text = "Generated by boomi-solace-migrate"

    obj = ET.SubElement(root, qname(BNS, "object"))
    config = ET.SubElement(obj, "GenericConnectionConfig")

    field_values = {
        "host": values.host,
        "vpn": values.vpn,
        "username": values.username,
        "password": values.password,
    }
    for logical_name, value in field_values.items():
        field_id = profile.connection_fields[logical_name]
        field_type = "password" if logical_name == "password" else "string"
        ET.SubElement(config, "field", {"id": field_id, "type": field_type, "value": value})

    return tostring(root)


def build_operation_xml(
    *,
    name: str,
    folder_id: str,
    profile: ConnectorProfile,
    action: str,
    destination: str,
    destination_type: str,
    delivery_mode: str,
) -> str:
    action_key = action.lower()
    if action_key not in ("send", "listen", "get"):
        raise ValueError(f"Unsupported action: {action}")

    root = ET.Element(
        qname(BNS, "Component"),
        {
            "componentId": "",
            "version": "1",
            "name": name,
            "type": "connector-action",
            "subType": profile.sub_type,
            "folderId": folder_id,
        },
    )
    ET.SubElement(root, qname(BNS, "encryptedValues"))
    ET.SubElement(root, qname(BNS, "description")).text = "Generated by boomi-solace-migrate"

    obj = ET.SubElement(root, qname(BNS, "object"))

    if action_key == "send":
        op_attrs = {"returnApplicationErrors": "false", "trackResponse": "false"}
        generic_attrs = {
            "operationType": "CREATE",
            "requestProfileType": "binary",
            "responseProfileType": "binary",
        }
    elif action_key == "listen":
        op_attrs = {"returnApplicationErrors": "false", "trackResponse": "true"}
        generic_attrs = {
            "operationType": "Listen",
            "requestProfileType": "binary",
            "responseProfileType": "binary",
        }
    else:
        op_attrs = {"returnApplicationErrors": "false", "trackResponse": "true"}
        generic_attrs = {
            "operationType": "GET",
            "requestProfileType": "binary",
            "responseProfileType": "binary",
        }

    operation = ET.SubElement(obj, "Operation", op_attrs)
    ET.SubElement(operation, "Archiving", {"directory": "", "enabled": "false"})
    configuration = ET.SubElement(operation, "Configuration")
    generic = ET.SubElement(configuration, "GenericOperationConfig", generic_attrs)

    if action_key == "send":
        ET.SubElement(generic, "field", {"id": "mode", "type": "string", "value": delivery_mode})
        ET.SubElement(generic, "field", {"id": "endpointType", "type": "string", "value": destination_type.lower()})
        ET.SubElement(generic, "field", {"id": "destination", "type": "string", "value": destination})
    elif action_key == "listen":
        ET.SubElement(generic, "field", {"id": "mode", "type": "string", "value": "PERSISTENT_TRANSACTED"})
        ET.SubElement(generic, "field", {"id": "destination", "type": "string", "value": destination})
        ET.SubElement(generic, "field", {"id": "batchSize", "type": "integer", "value": "500"})
        ET.SubElement(generic, "field", {"id": "receiveTimeout", "type": "integer", "value": "10000"})
        ET.SubElement(generic, "field", {"id": "maxConcurrentExecutions", "type": "integer", "value": "3"})
        ET.SubElement(generic, "field", {"id": "selector", "type": "string", "value": ""})
    else:
        ET.SubElement(generic, "field", {"id": "mode", "type": "string", "value": "PERSISTENT_TRANSACTED"})
        ET.SubElement(generic, "field", {"id": "destination", "type": "string", "value": destination})

    ET.SubElement(generic, "Options")
    tracking = ET.SubElement(operation, "Tracking")
    ET.SubElement(tracking, "TrackedFields")
    ET.SubElement(operation, "Caching")

    return tostring(root)
